### ISSUE TITLE
Could not create the environment

### ISSUE THREAD

**Issue by ahmetgorkemer** [i6092467/vadesc#1]
Hi,
I could not create the conda environment by using .yml file, it raised an error. Could you please check it?

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/Users/ahmetgorkemer/opt/anaconda3/lib/python3.9/site-packages/conda/exceptions.py", line 1118, in __call__
        return func(*args, **kwargs)
      File "/Users/ahmetgorkemer/opt/anaconda3/lib/python3.9/site-packages/conda_env/cli/main.py", line 78, in do_call
        exit_code = getattr(module, func_name)(args, parser)
      File "/Users/ahmetgorkemer/opt/anaconda3/lib/python3.9/site-packages/conda/notices/core.py", line 109, in wrapper
        return func(*args, **kwargs)
      File "/Users/ahmetgorkemer/opt/anaconda3/lib/python3.9/site-packages/conda_env/cli/main_create.py", line 101, in execute
        spec = specs.detect(name=name, filename=get_filename(args.file), directory=os.getcwd())
      File "/Users/ahmetgorkemer/opt/anaconda3/lib/python3.9/site-packages/conda_env/specs/__init__.py", line 46, in detect
        if spec.can_handle():
      File "/Users/ahmetgorkemer/opt/anaconda3/lib/python3.9/site-packages/conda_env/specs/yaml_file.py", line 18, in can_handle
        self._environment = env.from_file(self.filename)
      File "/Users/ahmetgorkemer/opt/anaconda3/lib/python3.9/site-packages/conda_env/env.py", line 169, in from_file
        return from_yaml(yamlstr, filename=filename)
      File "/Users/ahmetgorkemer/opt/anaconda3/lib/python3.9/site-packages/conda_env/env.py", line 143, in from_yaml
        data = yaml_safe_load(yamlstr)
      File "/Users/ahmetgorkemer/opt/anaconda3/lib/python3.9/site-packages/conda/common/serialize.py", line 67, in yaml_safe_load
        return _yaml_safe().load(string)
      File "/Users/ahmetgorkemer/opt/anaconda3/lib/python3.9/site-packages/ruamel/yaml/main.py", line 434, in load
        return constructor.get_single_data()
      File "/Users/ahmetgorkemer/opt/anaconda3/lib/python3.9/site-packages/ruamel/yaml/constructor.py", line 119, in get_single_data
        node = self.composer.get_single_node()
      File "/Users/ahmetgorkemer/opt/anaconda3/lib/python3.9/site-packages/ruamel/yaml/composer.py", line 76, in get_single_node
        document = self.compose_document()
      File "/Users/ahmetgorkemer/opt/anaconda3/lib/python3.9/site-packages/ruamel/yaml/composer.py", line 102, in compose_document
        self.parser.get_event()
      File "/Users/ahmetgorkemer/opt/anaconda3/lib/python3.9/site-packages/ruamel/yaml/parser.py", line 168, in get_event
        self.current_event = self.state()
      File "/Users/ahmetgorkemer/opt/anaconda3/lib/python3.9/site-packages/ruamel/yaml/parser.py", line 253, in parse_document_end
        token = self.scanner.peek_token()
      File "/Users/ahmetgorkemer/opt/anaconda3/lib/python3.9/site-packages/ruamel/yaml/scanner.py", line 188, in peek_token
        self.fetch_more_tokens()
      File "/Users/ahmetgorkemer/opt/anaconda3/lib/python3.9/site-packages/ruamel/yaml/scanner.py", line 288, in fetch_more_tokens
        return self.fetch_value()
      File "/Users/ahmetgorkemer/opt/anaconda3/lib/python3.9/site-packages/ruamel/yaml/scanner.py", line 657, in fetch_value
        raise ScannerError(
    ruamel.yaml.scanner.ScannerError: mapping values are not allowed here
      in "<unicode string>", line 28, column 66:
         ... le" content="{&quot;groups&quot;: [], &quot;environmentKey&quot; ... 
                                             ^ (line: 28)

**Comment by i6092467** [comment]
Hi,

What commands are you using to build the environment, and what operating system are you running?

**Comment by ahmetgorkemer** [comment]
It seems that dome dependencies do not work with M1 architecture. Now it works on Linux, thank you!
